### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by urishitapandita** [robert-z/code-snapshot#30]
There should be a download option, copy doesn't work every time.

**Comment by KiaBoluki** [comment]
what do you mean ? it saves the image when you click on the lens like button
![2022-06-17_01-10-41](https://user-images.githubusercontent.com/11926947/174164304-ad7093e6-94ba-4ba1-9abc-b7d605fb0c6f.gif)
.

**Comment by urishitapandita** [comment]
Yes! Got it now.

**Comment by mohits** [comment]
Hi @urishitapandita - would you close the issue please?
